"""Generate reference OCI request signatures with Oracle's official Python SDK.

Output: test/fixtures/signer-reference.json (consumed by test/signer.test.ts).
The key pair is generated fresh and is TEST-ONLY; it is not registered anywhere.

Run (from worker/):
  python3 -m venv .venv && .venv/bin/pip install -q oci==2.187.2 && .venv/bin/python -I scripts/gen-signer-fixtures.py
"""
import base64
import hashlib
import json
import os

from oci._vendor import requests
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from oci.signer import Signer

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "test", "fixtures", "signer-reference.json")
TENANCY = "ocid1.tenancy.oc1..aaaaaaaatesttenancyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
USER = "ocid1.user.oc1..aaaaaaaatestuserxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
DATE = "Thu, 05 Jan 2014 21:31:40 GMT"

key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
private_pem = key.private_bytes(
    serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()
).decode()
public_der = key.public_key().public_bytes(
    serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
)
public_pem = key.public_key().public_bytes(
    serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
).decode()
# OCI fingerprint: MD5 over the DER-encoded public key, colon-separated hex.
fingerprint = ":".join(f"{b:02x}" for b in hashlib.md5(public_der).digest())

signer = Signer(tenancy=TENANCY, user=USER, fingerprint=fingerprint,
                private_key_file_location=None, private_key_content=private_pem)

DOC_GET_URL = (
    "https://iaas.us-phoenix-1.oraclecloud.com/20160918/instances"
    "?availabilityDomain=Pjwf%3A%20PHX-AD-1"
    "&compartmentId=ocid1.compartment.oc1..aaaaaaaam3we6vgnherjq5q2idnccdflvjsnog7mlr6rtdb25gilchfeyjxa"
    "&displayName=TeamXInstances"
    "&volumeId=ocid1.volume.oc1.phx.abyhqljrgvttnlx73nmrwfaux7kcvzfs3s66izvxf2h4lgvyndsdsnoiwr5q"
)

CASES = [
    ("get-doc-example", "GET", DOC_GET_URL, None),
    ("get-region-subscriptions", "GET",
     f"https://identity.us-ashburn-1.oraclecloud.com/20160918/tenancies/{TENANCY}/regionSubscriptions", None),
    ("head", "HEAD", "https://iaas.us-ashburn-1.oraclecloud.com/20160918/instances/ocid1.instance.oc1.iad.xyz", None),
    ("delete", "DELETE", "https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns/ocid1.vcn.oc1.iad.xyz", None),
    ("post-json", "POST", "https://iaas.us-ashburn-1.oraclecloud.com/20160918/instances/",
     json.dumps({"compartmentId": TENANCY, "shape": "VM.Standard.A1.Flex",
                 "shapeConfig": {"ocpus": 2, "memoryInGBs": 12}, "displayName": "easycloud-a1"})),
    ("post-empty-body", "POST",
     "https://iaas.us-ashburn-1.oraclecloud.com/20160918/instances/ocid1.instance.oc1.iad.xyz?action=START", ""),
    ("put-utf8-body", "PUT", "https://iaas.us-ashburn-1.oraclecloud.com/20160918/vcns/ocid1.vcn.oc1.iad.xyz",
     json.dumps({"displayName": "café ☁️ easycloud"}, ensure_ascii=False)),
    ("patch-json", "PATCH", "https://identity.us-ashburn-1.oraclecloud.com/20160918/users/ocid1.user.oc1..xyz",
     json.dumps({"description": "patched"})),
]

cases = []
for name, method, url, body in CASES:
    req = requests.Request(method, url, headers={"date": DATE},
                           data=body.encode("utf-8") if body is not None else None)
    prepared = req.prepare()
    if body is not None:
        # Feed the SDK a str body so it computes content-length/sha256 itself (its str branch).
        prepared.body = body
        prepared.headers.pop("Content-Length", None)
    signer(prepared)
    h = {k.lower(): v for k, v in prepared.headers.items()}
    cases.append({
        "name": name,
        "method": method,
        "url": prepared.url,
        "date": DATE,
        "body": body,
        "expected": {
            "authorization": h["authorization"],
            "content-length": h.get("content-length"),
            "content-type": h.get("content-type"),
            "x-content-sha256": h.get("x-content-sha256"),
        },
    })

doc = {
    "_comment": "Generated by scripts/gen-signer-fixtures.py with oci==2.187.2. TEST-ONLY key; never registered.",
    "tenancy": TENANCY,
    "user": USER,
    "fingerprint": fingerprint,
    "privateKeyPem": private_pem,
    "publicKeyPem": public_pem,
    "cases": cases,
}
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(doc, f, indent=2, ensure_ascii=False)
    f.write("\n")
print(f"wrote {len(cases)} cases to {os.path.normpath(OUT)}")
